<?xml version="1.0" encoding="utf-8"?><Database Name="QL_NhaTro" Class="QLPTDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-GQAMABND;Initial Catalog=QL_NhaTro;User ID=sa" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="QL_NhaTroConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DICHVU" Member="DICHVUs">
    <Type Name="DICHVU">
      <Column Name="MADV" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DAXOA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CHISODIENNUOC" Member="CHISODIENNUOCs">
    <Type Name="CHISODIENNUOC">
      <Column Name="MACS" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MAPT" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYTHANG" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="CHISODIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CHISONUOC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PHONGTRO_CHISODIENNUOC" Member="PHONGTRO" ThisKey="MAPT" OtherKey="MAPT" Type="PHONGTRO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONGTRO" Member="PHONGTROs">
    <Type Name="PHONGTRO">
      <Column Name="MAPT" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANT" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MATT" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENPHONG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CHIEUDAI" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CHIEURONG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SOLUONGNGUOITD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ANH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DAXOA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="PHONGTRO_CHISODIENNUOC" Member="CHISODIENNUOCs" ThisKey="MAPT" OtherKey="MAPT" Type="CHISODIENNUOC" />
    </Type>
  </Table>
  <Table Name="dbo.QUANLY" Member="QUANLies">
    <Type Name="QUANLY">
      <Column Name="MAQL" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HOTENNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHINV" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SODT" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="EMAILNV" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ANH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NGAYVAO" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>