#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_NhaTro")]
	public partial class QLPTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDICHVU(DICHVU instance);
    partial void UpdateDICHVU(DICHVU instance);
    partial void DeleteDICHVU(DICHVU instance);
    partial void InsertCHISODIENNUOC(CHISODIENNUOC instance);
    partial void UpdateCHISODIENNUOC(CHISODIENNUOC instance);
    partial void DeleteCHISODIENNUOC(CHISODIENNUOC instance);
    partial void InsertPHONGTRO(PHONGTRO instance);
    partial void UpdatePHONGTRO(PHONGTRO instance);
    partial void DeletePHONGTRO(PHONGTRO instance);
    partial void InsertQUANLY(QUANLY instance);
    partial void UpdateQUANLY(QUANLY instance);
    partial void DeleteQUANLY(QUANLY instance);
    #endregion
		
		public QLPTDataContext() : 
				base(global::DAL.Properties.Settings.Default.QL_NhaTroConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public QLPTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLPTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLPTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLPTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DICHVU> DICHVUs
		{
			get
			{
				return this.GetTable<DICHVU>();
			}
		}
		
		public System.Data.Linq.Table<CHISODIENNUOC> CHISODIENNUOCs
		{
			get
			{
				return this.GetTable<CHISODIENNUOC>();
			}
		}
		
		public System.Data.Linq.Table<PHONGTRO> PHONGTROs
		{
			get
			{
				return this.GetTable<PHONGTRO>();
			}
		}
		
		public System.Data.Linq.Table<QUANLY> QUANLies
		{
			get
			{
				return this.GetTable<QUANLY>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DICHVU")]
	public partial class DICHVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MADV;
		
		private string _TENDV;
		
		private System.Nullable<decimal> _DONGIA;
		
		private string _MOTA;
		
		private bool _DAXOA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADVChanging(string value);
    partial void OnMADVChanged();
    partial void OnTENDVChanging(string value);
    partial void OnTENDVChanged();
    partial void OnDONGIAChanging(System.Nullable<decimal> value);
    partial void OnDONGIAChanged();
    partial void OnMOTAChanging(string value);
    partial void OnMOTAChanged();
    partial void OnDAXOAChanging(bool value);
    partial void OnDAXOAChanged();
    #endregion
		
		public DICHVU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADV", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADV
		{
			get
			{
				return this._MADV;
			}
			set
			{
				if ((this._MADV != value))
				{
					this.OnMADVChanging(value);
					this.SendPropertyChanging();
					this._MADV = value;
					this.SendPropertyChanged("MADV");
					this.OnMADVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDV", DbType="NVarChar(50)")]
		public string TENDV
		{
			get
			{
				return this._TENDV;
			}
			set
			{
				if ((this._TENDV != value))
				{
					this.OnTENDVChanging(value);
					this.SendPropertyChanging();
					this._TENDV = value;
					this.SendPropertyChanged("TENDV");
					this.OnTENDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Money")]
		public System.Nullable<decimal> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA", DbType="NVarChar(255)")]
		public string MOTA
		{
			get
			{
				return this._MOTA;
			}
			set
			{
				if ((this._MOTA != value))
				{
					this.OnMOTAChanging(value);
					this.SendPropertyChanging();
					this._MOTA = value;
					this.SendPropertyChanged("MOTA");
					this.OnMOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAXOA", DbType="Bit NOT NULL")]
		public bool DAXOA
		{
			get
			{
				return this._DAXOA;
			}
			set
			{
				if ((this._DAXOA != value))
				{
					this.OnDAXOAChanging(value);
					this.SendPropertyChanging();
					this._DAXOA = value;
					this.SendPropertyChanged("DAXOA");
					this.OnDAXOAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHISODIENNUOC")]
	public partial class CHISODIENNUOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MACS;
		
		private string _MAPT;
		
		private System.DateTime _NGAYTHANG;
		
		private int _CHISODIEN;
		
		private int _CHISONUOC;
		
		private EntityRef<PHONGTRO> _PHONGTRO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACSChanging(int value);
    partial void OnMACSChanged();
    partial void OnMAPTChanging(string value);
    partial void OnMAPTChanged();
    partial void OnNGAYTHANGChanging(System.DateTime value);
    partial void OnNGAYTHANGChanged();
    partial void OnCHISODIENChanging(int value);
    partial void OnCHISODIENChanged();
    partial void OnCHISONUOCChanging(int value);
    partial void OnCHISONUOCChanged();
    #endregion
		
		public CHISODIENNUOC()
		{
			this._PHONGTRO = default(EntityRef<PHONGTRO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MACS
		{
			get
			{
				return this._MACS;
			}
			set
			{
				if ((this._MACS != value))
				{
					this.OnMACSChanging(value);
					this.SendPropertyChanging();
					this._MACS = value;
					this.SendPropertyChanged("MACS");
					this.OnMACSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPT", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MAPT
		{
			get
			{
				return this._MAPT;
			}
			set
			{
				if ((this._MAPT != value))
				{
					if (this._PHONGTRO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPTChanging(value);
					this.SendPropertyChanging();
					this._MAPT = value;
					this.SendPropertyChanged("MAPT");
					this.OnMAPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTHANG", DbType="Date NOT NULL")]
		public System.DateTime NGAYTHANG
		{
			get
			{
				return this._NGAYTHANG;
			}
			set
			{
				if ((this._NGAYTHANG != value))
				{
					this.OnNGAYTHANGChanging(value);
					this.SendPropertyChanging();
					this._NGAYTHANG = value;
					this.SendPropertyChanged("NGAYTHANG");
					this.OnNGAYTHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHISODIEN", DbType="Int NOT NULL")]
		public int CHISODIEN
		{
			get
			{
				return this._CHISODIEN;
			}
			set
			{
				if ((this._CHISODIEN != value))
				{
					this.OnCHISODIENChanging(value);
					this.SendPropertyChanging();
					this._CHISODIEN = value;
					this.SendPropertyChanged("CHISODIEN");
					this.OnCHISODIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHISONUOC", DbType="Int NOT NULL")]
		public int CHISONUOC
		{
			get
			{
				return this._CHISONUOC;
			}
			set
			{
				if ((this._CHISONUOC != value))
				{
					this.OnCHISONUOCChanging(value);
					this.SendPropertyChanging();
					this._CHISONUOC = value;
					this.SendPropertyChanged("CHISONUOC");
					this.OnCHISONUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGTRO_CHISODIENNUOC", Storage="_PHONGTRO", ThisKey="MAPT", OtherKey="MAPT", IsForeignKey=true)]
		public PHONGTRO PHONGTRO
		{
			get
			{
				return this._PHONGTRO.Entity;
			}
			set
			{
				PHONGTRO previousValue = this._PHONGTRO.Entity;
				if (((previousValue != value) 
							|| (this._PHONGTRO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONGTRO.Entity = null;
						previousValue.CHISODIENNUOCs.Remove(this);
					}
					this._PHONGTRO.Entity = value;
					if ((value != null))
					{
						value.CHISODIENNUOCs.Add(this);
						this._MAPT = value.MAPT;
					}
					else
					{
						this._MAPT = default(string);
					}
					this.SendPropertyChanged("PHONGTRO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONGTRO")]
	public partial class PHONGTRO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPT;
		
		private string _MANT;
		
		private string _MATT;
		
		private string _TENPHONG;
		
		private System.Nullable<decimal> _DONGIA;
		
		private System.Nullable<double> _CHIEUDAI;
		
		private System.Nullable<double> _CHIEURONG;
		
		private System.Nullable<int> _SOLUONGNGUOITD;
		
		private string _MOTA;
		
		private string _ANH;
		
		private bool _DAXOA;
		
		private EntitySet<CHISODIENNUOC> _CHISODIENNUOCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPTChanging(string value);
    partial void OnMAPTChanged();
    partial void OnMANTChanging(string value);
    partial void OnMANTChanged();
    partial void OnMATTChanging(string value);
    partial void OnMATTChanged();
    partial void OnTENPHONGChanging(string value);
    partial void OnTENPHONGChanged();
    partial void OnDONGIAChanging(System.Nullable<decimal> value);
    partial void OnDONGIAChanged();
    partial void OnCHIEUDAIChanging(System.Nullable<double> value);
    partial void OnCHIEUDAIChanged();
    partial void OnCHIEURONGChanging(System.Nullable<double> value);
    partial void OnCHIEURONGChanged();
    partial void OnSOLUONGNGUOITDChanging(System.Nullable<int> value);
    partial void OnSOLUONGNGUOITDChanged();
    partial void OnMOTAChanging(string value);
    partial void OnMOTAChanged();
    partial void OnANHChanging(string value);
    partial void OnANHChanged();
    partial void OnDAXOAChanging(bool value);
    partial void OnDAXOAChanged();
    #endregion
		
		public PHONGTRO()
		{
			this._CHISODIENNUOCs = new EntitySet<CHISODIENNUOC>(new Action<CHISODIENNUOC>(this.attach_CHISODIENNUOCs), new Action<CHISODIENNUOC>(this.detach_CHISODIENNUOCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPT", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPT
		{
			get
			{
				return this._MAPT;
			}
			set
			{
				if ((this._MAPT != value))
				{
					this.OnMAPTChanging(value);
					this.SendPropertyChanging();
					this._MAPT = value;
					this.SendPropertyChanged("MAPT");
					this.OnMAPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANT", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MANT
		{
			get
			{
				return this._MANT;
			}
			set
			{
				if ((this._MANT != value))
				{
					this.OnMANTChanging(value);
					this.SendPropertyChanging();
					this._MANT = value;
					this.SendPropertyChanged("MANT");
					this.OnMANTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATT", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MATT
		{
			get
			{
				return this._MATT;
			}
			set
			{
				if ((this._MATT != value))
				{
					this.OnMATTChanging(value);
					this.SendPropertyChanging();
					this._MATT = value;
					this.SendPropertyChanged("MATT");
					this.OnMATTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENPHONG", DbType="NVarChar(30)")]
		public string TENPHONG
		{
			get
			{
				return this._TENPHONG;
			}
			set
			{
				if ((this._TENPHONG != value))
				{
					this.OnTENPHONGChanging(value);
					this.SendPropertyChanging();
					this._TENPHONG = value;
					this.SendPropertyChanged("TENPHONG");
					this.OnTENPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Money")]
		public System.Nullable<decimal> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHIEUDAI", DbType="Float")]
		public System.Nullable<double> CHIEUDAI
		{
			get
			{
				return this._CHIEUDAI;
			}
			set
			{
				if ((this._CHIEUDAI != value))
				{
					this.OnCHIEUDAIChanging(value);
					this.SendPropertyChanging();
					this._CHIEUDAI = value;
					this.SendPropertyChanged("CHIEUDAI");
					this.OnCHIEUDAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHIEURONG", DbType="Float")]
		public System.Nullable<double> CHIEURONG
		{
			get
			{
				return this._CHIEURONG;
			}
			set
			{
				if ((this._CHIEURONG != value))
				{
					this.OnCHIEURONGChanging(value);
					this.SendPropertyChanging();
					this._CHIEURONG = value;
					this.SendPropertyChanged("CHIEURONG");
					this.OnCHIEURONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONGNGUOITD", DbType="Int")]
		public System.Nullable<int> SOLUONGNGUOITD
		{
			get
			{
				return this._SOLUONGNGUOITD;
			}
			set
			{
				if ((this._SOLUONGNGUOITD != value))
				{
					this.OnSOLUONGNGUOITDChanging(value);
					this.SendPropertyChanging();
					this._SOLUONGNGUOITD = value;
					this.SendPropertyChanged("SOLUONGNGUOITD");
					this.OnSOLUONGNGUOITDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA", DbType="NVarChar(255)")]
		public string MOTA
		{
			get
			{
				return this._MOTA;
			}
			set
			{
				if ((this._MOTA != value))
				{
					this.OnMOTAChanging(value);
					this.SendPropertyChanging();
					this._MOTA = value;
					this.SendPropertyChanged("MOTA");
					this.OnMOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANH", DbType="NVarChar(MAX)")]
		public string ANH
		{
			get
			{
				return this._ANH;
			}
			set
			{
				if ((this._ANH != value))
				{
					this.OnANHChanging(value);
					this.SendPropertyChanging();
					this._ANH = value;
					this.SendPropertyChanged("ANH");
					this.OnANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAXOA", DbType="Bit NOT NULL")]
		public bool DAXOA
		{
			get
			{
				return this._DAXOA;
			}
			set
			{
				if ((this._DAXOA != value))
				{
					this.OnDAXOAChanging(value);
					this.SendPropertyChanging();
					this._DAXOA = value;
					this.SendPropertyChanged("DAXOA");
					this.OnDAXOAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGTRO_CHISODIENNUOC", Storage="_CHISODIENNUOCs", ThisKey="MAPT", OtherKey="MAPT")]
		public EntitySet<CHISODIENNUOC> CHISODIENNUOCs
		{
			get
			{
				return this._CHISODIENNUOCs;
			}
			set
			{
				this._CHISODIENNUOCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHISODIENNUOCs(CHISODIENNUOC entity)
		{
			this.SendPropertyChanging();
			entity.PHONGTRO = this;
		}
		
		private void detach_CHISODIENNUOCs(CHISODIENNUOC entity)
		{
			this.SendPropertyChanging();
			entity.PHONGTRO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUANLY")]
	public partial class QUANLY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAQL;
		
		private string _HOTENNV;
		
		private string _DIACHINV;
		
		private string _SODT;
		
		private string _EMAILNV;
		
		private string _ANH;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private System.Nullable<System.DateTime> _NGAYVAO;
		
		private string _MATKHAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAQLChanging(string value);
    partial void OnMAQLChanged();
    partial void OnHOTENNVChanging(string value);
    partial void OnHOTENNVChanged();
    partial void OnDIACHINVChanging(string value);
    partial void OnDIACHINVChanged();
    partial void OnSODTChanging(string value);
    partial void OnSODTChanged();
    partial void OnEMAILNVChanging(string value);
    partial void OnEMAILNVChanged();
    partial void OnANHChanging(string value);
    partial void OnANHChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnNGAYVAOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYVAOChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    #endregion
		
		public QUANLY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAQL", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAQL
		{
			get
			{
				return this._MAQL;
			}
			set
			{
				if ((this._MAQL != value))
				{
					this.OnMAQLChanging(value);
					this.SendPropertyChanging();
					this._MAQL = value;
					this.SendPropertyChanged("MAQL");
					this.OnMAQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENNV", DbType="NVarChar(50)")]
		public string HOTENNV
		{
			get
			{
				return this._HOTENNV;
			}
			set
			{
				if ((this._HOTENNV != value))
				{
					this.OnHOTENNVChanging(value);
					this.SendPropertyChanging();
					this._HOTENNV = value;
					this.SendPropertyChanged("HOTENNV");
					this.OnHOTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHINV", DbType="NVarChar(100)")]
		public string DIACHINV
		{
			get
			{
				return this._DIACHINV;
			}
			set
			{
				if ((this._DIACHINV != value))
				{
					this.OnDIACHINVChanging(value);
					this.SendPropertyChanging();
					this._DIACHINV = value;
					this.SendPropertyChanged("DIACHINV");
					this.OnDIACHINVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODT", DbType="NVarChar(20)")]
		public string SODT
		{
			get
			{
				return this._SODT;
			}
			set
			{
				if ((this._SODT != value))
				{
					this.OnSODTChanging(value);
					this.SendPropertyChanging();
					this._SODT = value;
					this.SendPropertyChanged("SODT");
					this.OnSODTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAILNV", DbType="NVarChar(30)")]
		public string EMAILNV
		{
			get
			{
				return this._EMAILNV;
			}
			set
			{
				if ((this._EMAILNV != value))
				{
					this.OnEMAILNVChanging(value);
					this.SendPropertyChanging();
					this._EMAILNV = value;
					this.SendPropertyChanged("EMAILNV");
					this.OnEMAILNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANH", DbType="NVarChar(MAX)")]
		public string ANH
		{
			get
			{
				return this._ANH;
			}
			set
			{
				if ((this._ANH != value))
				{
					this.OnANHChanging(value);
					this.SendPropertyChanging();
					this._ANH = value;
					this.SendPropertyChanged("ANH");
					this.OnANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYVAO", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYVAO
		{
			get
			{
				return this._NGAYVAO;
			}
			set
			{
				if ((this._NGAYVAO != value))
				{
					this.OnNGAYVAOChanging(value);
					this.SendPropertyChanging();
					this._NGAYVAO = value;
					this.SendPropertyChanged("NGAYVAO");
					this.OnNGAYVAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="NVarChar(512) NOT NULL", CanBeNull=false)]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
